name: Facebook History Bot

on:
  schedule:
    - cron: "0 7,13,19 * * *"   # 07:00, 13:00, 19:00 UTC
  workflow_dispatch: # allow manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Facebook Bot
        env:
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python facebook_bot.py
