name: Daily Facebook Bot

on:
  schedule:
    # Runs at 07:00, 13:00, and 19:00 UTC daily
    - cron: '0 7,13,19 * * *'
  workflow_dispatch: # allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
      FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests schedule

      - name: Run Facebook Bot
        run: |
          python facebook_bot.py
